
/**
 * Action Types
 */

export const FETCH_USER_LOCATION = 'FETCH_USER_LOCATION'
export const GET_USER_LOCATION = 'GET_USER_LOCATION'
export const FETCH_MUNICIPALITIES = 'FETCH_MUNICIPALITIES'
export const CHOOSE_MUNICIPALITY = 'CHOOSE_MUNICIPALITY'
export const FILTER_MUNICIPALITIES = 'FILTER_MUNICIPALITIES'
export const SET_INITIAL_MUNICIPALITIES = 'SET_INITIAL_MUNICIPALITIES'
export const SHOW_USER_LOCATION = 'SHOW_USER_LOCATION'
export const SHOW_USER_LOCATION_ERROR = 'SHOW_USER_LOCATION_ERROR'
export const RESET_USER_LOCATION = 'RESET_USER_LOCATION'
export const SET_FILTERS_FROM_URL = 'SET_FILTERS_FROM_URL'
export const FETCH_AREA = 'FETCH_AREA'
export const SELECT_AREA = 'SELECT_AREA'
export const FETCH_SEARCH = 'FETCH_SEARCH'
export const SEARCH = 'SEARCH'
export const TOGGLE_DRAWER = 'TOGGLE_DRAWER'
export const UPDATE_FILTERS = 'UPDATE_FILTERS'
export const RESET_FILTERS = 'RESET_FILTERS'
export const UPDATE_QUERY = 'UPDATE_QUERY'
export const REMOVE_FILTERS = 'REMOVE_FILTERS'
export const RESET_QUERY = 'RESET_QUERY'