
/**
 * Action Types
 */

export const FETCH_USER_LOCATION = 'FETCH_USER_LOCATION'
export const GET_USER_LOCATION = 'GET_USER_LOCATION'
export const FETCH_MUNICIPALITIES = 'FETCH_MUNICIPALITIES'
export const CHOOSE_MUNICIPALITY = 'CHOOSE_MUNICIPALITY'
export const FILTER_MUNICIPALITIES = 'FILTER_MUNICIPALITIES'
export const SET_INITIAL_MUNICIPALITIES = 'SET_INITIAL_MUNICIPALITIES'
export const SHOW_USER_LOCATION = 'SHOW_USER_LOCATION'
export const SHOW_USER_LOCATION_ERROR = 'SHOW_USER_LOCATION_ERROR'
export const RESET_USER_LOCATION = 'RESET_USER_LOCATION'