/**
 * Action Types
 */

export const FETCH_USER_LOCATION = 'FETCH_USER_LOCATION';
export const GET_USER_LOCATION = 'GET_USER_LOCATION';
export const FETCH_MUNICIPALITIES = 'FETCH_MUNICIPALITIES';
export const CHOOSE_MUNICIPALITY = 'CHOOSE_MUNICIPALITY';
export const FILTER_MUNICIPALITIES = 'FILTER_MUNICIPALITIES';
export const SET_INITIAL_MUNICIPALITIES = 'SET_INITIAL_MUNICIPALITIES';
export const SHOW_USER_LOCATION = 'SHOW_USER_LOCATION';
export const SHOW_USER_LOCATION_FAILED = 'SHOW_USER_LOCATION_FAILED';
export const SET_FILTERS_FROM_URL = 'SET_FILTERS_FROM_URL';
export const FETCH_AREA = 'FETCH_AREA';
export const SELECT_AREA = 'SELECT_AREA';
export const FETCH_SEARCH = 'FETCH_SEARCH';
export const SEARCH = 'SEARCH';
export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';
export const UPDATE_FILTERS = 'UPDATE_FILTERS';
export const RESET_FILTERS = 'RESET_FILTERS';
export const UPDATE_QUERY = 'UPDATE_QUERY';
export const REMOVE_FILTERS = 'REMOVE_FILTERS';
export const RESET_QUERY = 'RESET_QUERY';
export const GET_MORE_DOCS = 'GET_MORE_DOCS';
export const FETCH_MORE_DOCS = 'FETCH_MORE_DOCS';
export const SET_CODE = 'SET_CODE';
export const RESET_AREA = 'RESET_AREA';
export const RESET_LOCATION = 'RESET_LOCATION';
export const FETCH_RESET_FILTERS = 'FETCH_RESET_FILTERS';
export const FETCH_INITIAL_LOCATION = 'FETCH_INITIAL_LOCATION';
export const FETCH_UPDATE_QUERY = 'FETCH_UPDATE_QUERY';
export const FETCH_REMOVE_FILTERS = 'FETCH_REMOVE_FILTERS';
export const FETCH_TOGGLE_DRAWER = 'FETCH_TOGGLE_DRAWER';
export const FETCH_RESET_AREA = 'FETCH_RESET_AREA';
export const FETCH_AREA_FAILED = 'FETCH_AREA_FAILED';
export const FETCH_ADJACENT_AREA = 'FETCH_ADJACENT_AREA';
export const FETCH_SEARCH_FAILED = 'FETCH_SEARCH_FAILED';
export const FETCH_INITIAL_LOCATION_FAILED = 'FETCH_INITIAL_LOCATION_FAILED';
export const SUBMIT_ALERT = 'SUBMIT_ALERT';
export const POST_ALERT_SUBSCRIPTION = 'POST_ALERT_SUBSCRIPTION';
export const POST_ALERT_SUBSCRIPTION_FAILED = 'POST_ALERT_SUBSCRIPTION_FAILED';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const POST_USER_FEEDBACK = 'POST_USER_FEEDBACK';
export const USER_FEEDBACK_POST_FAILED = 'USER_FEEDBACK_POST_FAILED';
export const USER_FEEDBACK_SAVED = 'USER_FEEDBACK_SAVED';
